swagger: "2.0"
host: api.containership.io
basePath: /v3
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json

info:
  version: "3.0.0"
  title: Containership Cloud API
  contact:
    name: Containership Developers
    email: developers@containership.io
    url: https://containership.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /account:
    get:
      summary: Get user account info
      operationId: getAccount
      tags:
        - account
      responses:
        "200":
          description: User account info
          schema:
            $ref: "#/definitions/Account"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /plugins:
    get:
      summary: Get plugin catalog
      operationId: getPluginCatalog
      tags:
        - plugins-catalog
      responses:
        "200":
          description: Plugin catalog info
          schema:
            $ref: "#/definitions/PluginCatalog"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /plugins/{type}:
    get:
      summary: Get plugin catalog filtered by plugin type
      operationId: getPluginCatalogByType
      tags:
        - plugins-catalog
      parameters:
        - in: path
          name: type
          required: true
          type: string
      responses:
        "200":
          description: Plugin catalog info
          schema:
            type: array
            items:
              $ref: "#/definitions/PluginDefinition"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /plugins/{type}/implementations/{implementation}:
    get:
      summary: Get plugin catalog filtered by plugin type and implementation
      operationId: getPluginCatalogByTypeAndImplementation
      tags:
        - plugins-catalog
      parameters:
        - in: path
          name: type
          required: true
          type: string
        - in: path
          name: implementation
          required: true
          type: string
      responses:
        "200":
          description: Plugin catalog info
          schema:
            $ref: "#/definitions/PluginDefinition"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /plugins/{type}/implementations/{implementation}/versions/{version}:
    get:
      summary: Get plugin catalog filtered by plugin type, implementation, and version
      operationId: getPluginCatalogByTypeImplementationAndVersion
      tags:
        - plugins-catalog
      parameters:
      - in: path
        name: type
        required: true
        type: string
      - in: path
        name: implementation
        required: true
        type: string
      - in: path
        name: version
        required: true
        type: string
      responses:
        "200":
          description: Plugin catalog info
          schema:
            $ref: "#/definitions/PluginVersion"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/clusters:
    get:
      summary: List all clusters (attached or provisioned through Containership) for a given organization
      operationId: listClusters
      tags:
        - clusters
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
      responses:
        "200":
          description: A list of clusters
          schema:
            $ref: "#/definitions/Clusters"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/clusters/{cluster_id}:
    get:
      summary: Get a cluster
      operationId: getCluster
      tags:
        - cluster
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
        - in: path
          name: cluster_id
          required: true
          type: string
      responses:
        "200":
          description: A cluster
          schema:
            $ref: "#/definitions/Cluster"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations:
    get:
      summary: List all organizations
      operationId: listOrganizations
      tags:
        - organizations
      responses:
        "200":
          description: A list of organizations
          schema:
            $ref: "#/definitions/Organizations"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}:
    get:
      summary: Get an organizations
      operationId: getOrganization
      tags:
        - organization
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
      responses:
        "200":
          description: An organization
          schema:
            $ref: "#/definitions/Organization"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/providers:
    get:
      summary: List all providers for a given organization
      operationId: listProviders
      tags:
        - providers
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
      responses:
        "200":
          description: A list of providers
          schema:
            $ref: "#/definitions/Providers"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/providers/{provider_id}:
    get:
      summary: Get a provider
      operationId: getProvider
      tags:
        - provider
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
        - in: path
          name: provider_id
          required: true
          type: string
      responses:
        "200":
          description: A provider
          schema:
            $ref: "#/definitions/Provider"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/clusters/{cluster_id}/plugins:
    get:
      summary: List all plugins for a cluster
      operationId: listPlugins
      tags:
        - plugins
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
        - in: path
          name: cluster_id
          required: true
          type: string
      responses:
        "200":
          description: A list of plugins
          schema:
            $ref: "#/definitions/Plugins"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/clusters/{cluster_id}/plugins/{plugin_id}:
    get:
      summary: Get a plugin
      operationId: getPlugin
      tags:
        - plugins
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
        - in: path
          name: cluster_id
          required: true
          type: string
        - in: path
          name: plugin_id
          required: true
          type: string
      responses:
        "200":
          description: A plugin
          schema:
            $ref: "#/definitions/Plugin"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/registries:
    get:
      summary: List registries for an organization
      operationId: listRegistries
      tags:
        - registries
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
      responses:
        "200":
          description: A list of registries
          schema:
            $ref: "#/definitions/Registries"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /organizations/{organization_id}/registries/{registry_id}:
    get:
      summary: Get a registry
      operationId: getRegistry
      tags:
        - registry
      parameters:
        - in: path
          name: organization_id
          required: true
          type: string
        - in: path
          name: registry_id
          required: true
          type: string
      responses:
        "200":
          description: A registry
          schema:
            $ref: "#/definitions/Registry"


definitions:
  Account:
    title: A user account
    type: object
    required:
      - id
      - created_at
      - updated_at
      - name
      - enabled
      - email
      - phone
      - avatar_url
    properties:
      id:
        title: Account ID
        $ref: "#/definitions/UUID"
      created_at:
        title: Timestamp at which the account was created
        type: string
      updated_at:
        title: Timestamp at which the account was updated
        type: string
      name:
        title: User name
        type: string
      enabled:
        title: Flag indicating if the account is enabled
        type: boolean
      email:
        title: Email associated with the account
        type: string
      phone:
        title: Phone number associated with the account
        type: string
      avatar_url:
        title: Avatar URL associated with the account
        type: string

  Cluster:
    title: A cluster attached or provisioned through Containership
    type: object
    required:
      - created_at
      - updated_at
      - id
      - organization_id
      - name
      - owner_id
      - api_server_address
      - worker_nodes_address
      - environment
      - version
      - provider_name
    properties:
      created_at:
        title: Timestamp at which the cluster was created
        type: string
      updated_at:
        title: Timestamp at which the cluster was updated
        type: string
      id:
        title: Cluster ID
        $ref: "#/definitions/UUID"
      organization_id:
        title: Organization ID of the organization the cluster belongs to
        $ref: "#/definitions/UUID"
      name:
        title: Cluster name
        type: string
      owner_id:
        title: Account ID of the cluster owner
        $ref: "#/definitions/UUID"
      api_server_address:
        title: API server address
        type: string
      worker_nodes_address:
        title: Worker nodes address
        type: string
      environment:
        title: Cluster environment
        type: string
      version:
        title: Kubernetes version
        type: string
      provider_name:
        title: Name of the provider through which the cluster is provisioned
        type: string

  Clusters:
    type: array
    items:
      $ref: "#/definitions/Cluster"

  Provider:
    title: A set of cloud provider credentials
    type: object
    required:
      - created_at
      - updated_at
      - id
      - organization_id
      - provider
      - description
    properties:
      created_at:
        title: Timestamp at which the provider was created
        type: string
      updated_at:
        title: Timestamp at which the provider was updated
        type: string
      id:
        title: Provider ID
        $ref: "#/definitions/UUID"
      organization_id:
        title: Organization ID of the organization the provider belongs to
        $ref: "#/definitions/UUID"
      provider:
        title: Provider name
        type: string
      description:
        title: Provider description
        type: string

  Providers:
    type: array
    items:
      $ref: "#/definitions/Provider"

  Organization:
    title: A Containership organization
    type: object
    required:
      - id
      - name
      - owner_id
      - created_at
      - updated_at
      - locked
    properties:
      id:
        title: Organization ID
        $ref: "#/definitions/UUID"
      name:
        title: Name of the organization (typically a company name)
        type: string
      owner_id:
        title: User ID of the organization owner
        $ref: "#/definitions/UUID"
      created_at:
        title: Timestamp at which the organization was created
        type: string
      updated_at:
        title: Timestamp at which the organization was updated
        type: string
      locked:
        title: Flag indicating if the organization is locked
        description: If this flag is set to true, support must be contacted in order to re-enable access.
        type: boolean

  Organizations:
    type: array
    items:
      $ref: "#/definitions/Organization"

  Plugin:
    title: A Containership plugin
    type: object
    required:
      - created_at
      - updated_at
      - id
      - type
      - implementation
      - version
      - organization_id
      - cluster_id
      - configuration
    properties:
      created_at:
        title: Timestamp at which the plugin was created
        type: string
      updated_at:
        title: Timestamp at which the plugin was updated
        type: string
      id:
        title: Plugin ID
        $ref: "#/definitions/UUID"
      type:
        title: Plugin type, e.g. metrics
        type: string
      implementation:
        title: Plugin implementation, e.g. prometheus
        type: string
      version:
        title: Plugin version
        type: string
      organization_id:
        title: Organization ID
        type: string
      cluster_id:
        title: Cluster ID
        type: string
      configuration:
        title: Plugin configuration (varies per-plugin)
        type: object

  PluginCatalog:
    title: A Containership plugin definition
    type: object
    properties:
      cloud_controller_manager:
        title: Cloud Controller Manager Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"
      cluster_management:
        title: Cluster Management Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"
      CNI:
        title: Container Network Interface (CNI) Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"
      CSI:
        title: Container Storage Interface (CSI) Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"
      logs:
        title: Log Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"
      metrics:
        title: Metric Plugins
        type: array
        x-omitempty: true
        items:
          $ref: "#/definitions/PluginDefinition"

  PluginDefinition:
    title: A Containership plugin definition
    type: object
    required:
      - type
      - implementation
      - versions
    properties:
      type:
        title: The type of plugin
        type: string
      implementation:
        title: The implementation of the type of plugin
        type: string
      versions:
        title: The version compatibility definition
        type: array
        items:
          $ref: "#/definitions/PluginVersion"

  PluginVersion:
    title: A Containership plugin version definition
    type: object
    required:
      - version
      - compatibility
      - configuration_schema
    properties:
      disabled:
        title: If the plugin is disabled
        type: boolean
      configuration_schema:
        title: Required configuration keys
        type: array
        items:
          type: string
      version:
        title: The plugin version
        type: string
      compatibility:
        title: Kubernetes and upgrade compatibility
        $ref: "#/definitions/PluginCompatibility"

  PluginCompatibility:
    title: A Containership plugin compatibility definition
    type: object
    required:
      - kubernetes
      - upgrades
    properties:
      upgrades:
        title: The list of valid upgrade paths for the plugin
        type: array
        items:
          type: string
      kubernetes:
        title: The definition for Kubernetes compatibility
        $ref: "#/definitions/PluginKubernetesCompatibility"

  PluginKubernetesCompatibility:
    title: Defines the Kubernetes version that the plugin supports
    type: object
    required:
      - min
      - max
    properties:
      min:
        title: The minimum Kubernetes version for the plugin
        type: string
      max:
        title: The maximum Kubernetes version for the plugin
        type: string

  Plugins:
    type: array
    items:
      $ref: "#/definitions/Plugin"

  Registry:
    title: A Containership registry
    type: object
    required:
      - created_at
      - description
      - id
      - organization_id
      - provider
      - serveraddress
      - updated_at
    properties:
      created_at:
        title: Timestamp at which the registry was added
        type: string
      description:
        title: Registry description
        type: string
      id:
        title: Registry ID
        $ref: "#/definitions/UUID"
      organization_id:
        title: Organization ID
        type: string
      provider:
        title: Registry provider, e.g. quay or dockerhub
        type: string
      serveraddress:
        title: Registry server address
        type: string
      updated_at:
        title: Timestamp at which the registry was updated
        type: string

  Registries:
    type: array
    items:
      $ref: "#/definitions/Registry"

  User:
    title: A user belonging to an organization
    type: object
    required:
      - id
      - name
      - email
      - avatar_url
      - added_at
      - ssh_keys
    properties:
      id:
        title: User ID
        $ref: "#/definitions/UUID"
      name:
        title: User name
        type: string
      email:
        title: User email
        type: string
      avatar_url:
        title: Avatar URL
        type: string
      added_at:
        title: Timestamp at which the user was created
        type: string
      ssh_keys:
        title: SSH Keys
        $ref: "#/definitions/SSHKeys"

  Users:
    type: array
    items:
      $ref: "#/definitions/User"

  SSHKey:
    title: An SSH key belonging to a user
    type: object
    required:
      - created_at
      - updated_at
      - id
      - user_id
      - name
      - fingerprint
      - key
    properties:
      created_at:
        title: Timestamp at which the key was created
        type: string
      updated_at:
        title: Timestamp at which the key was updated
        type: string
      id:
        title: SSH key ID
        $ref: "#/definitions/UUID"
      user_id:
        title: User ID of the associated user
        $ref: "#/definitions/UUID"
      name:
        title: Name of they key
        type: string
      fingerprint:
        title: Fingerprint of they key
        type: string
      key:
        title: Public key
        type: string

  SSHKeys:
    type: array
    items:
      $ref: "#/definitions/SSHKey"

  UUID:
    title: UUID
    type: string
    minLength: 36
    maxLength: 36
  
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
